// LOCALHOST 

// Users Endpoints
###
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/users/67a440f5e1706972dc9a8f70

###
POST http://localhost:8080/api/users/ HTTP/1.1
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Van",
  "favorites": [60, 56]
}

###
PUT http://localhost:8080/api/users/67a70ab07cc7e8f8bca84897 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "favorites": [116, 301, 86]
}


###
DELETE http://localhost:8080/api/users/67a440f5e1706972dc9a8f6f

// Hymns Endpoints
### 
GET http://localhost:8080/api/hymns

### 
GET http://localhost:8080/api/hymns/67a702aaba0ab2a9118ad05f

###
POST http://localhost:8080/api/hymns/ HTTP/1.1
Content-Type: application/json

{
  "title": "I Am a Child of God Test",
  "number": 301,
  "lyrics": "I am a child of God, and he has sent me here...",
  "composer": "Mildred T. Pettit",
  "topics": [
    "Children",
    "God's Love"
  ],
  "scriptures": "Romans 8:16",
  "webURL": "https://www.churchofjesuschrist.org/music/library/childrens-songbook/i-am-a-child-of-god"
}

###
PUT http://localhost:8080/api/hymns/67a70429936aa072f1deb89f HTTP/1.1
Content-Type: application/json

{
  "title": "Child of God",
  "number": 301,
  "lyrics": "I am a child of God, and he has sent me here...",
  "composer": "Mildred T. Pettit",
  "topics": [
    "Children",
    "God's Love"
  ],
  "scriptures": "Romans 8:16",
  "webURL": "https://www.churchofjesuschrist.org/music/library/childrens-songbook/i-am-a-child-of-god"
}

###
DELETE http://localhost:8080/api/hymns/67a703b5936aa072f1deb89b


// PRODUCTION

// Users Endpoints
###
GET https://hymnapi.onrender.com/api/users

###
GET https://hymnapi.onrender.com/api/users/67a440f5e1706972dc9a8f70

###
POST https://hymnapi.onrender.com/api/users/ HTTP/1.1
Content-Type: application/json

{
	"firstName": "Johanna",
    "lastName": "Sips",
    "favorites": [1,7,3]
}

PUT https://hymnapi.onrender.com/api/users/67a440f5e1706972dc9a8f70 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "favorites": [116, 301, 86]
}

###
DELETE https://hymnapi.onrender.com/api/users/67a440f5e1706972dc9a8f6f

// Hymns Endpoints
### 
GET https://hymnapi.onrender.com/api/hymns

### 
GET https://hymnapi.onrender.com/api/hymns/67a702aaba0ab2a9118ad05f

###
POST https://hymnapi.onrender.com/api/hymns/ HTTP/1.1
Content-Type: application/json

{
  "title": "I Am a Child of God Test",
  "number": 301,
  "lyrics": "I am a child of God, and he has sent me here...",
  "composer": "Mildred T. Pettit",
  "topics": [
    "Children",
    "God's Love"
  ],
  "scriptures": "Romans 8:16",
  "webURL": "https://www.churchofjesuschrist.org/music/library/childrens-songbook/i-am-a-child-of-god"
}

###
PUT https://hymnapi.onrender.com/api/hymns/67a70429936aa072f1deb89f HTTP/1.1
Content-Type: application/json

{
  "title": "Child of God",
  "number": 301,
  "lyrics": "I am a child of God, and he has sent me here...",
  "composer": "Mildred T. Pettit",
  "topics": [
    "Children",
    "God's Love"
  ],
  "scriptures": "Romans 8:16",
  "webURL": "https://www.churchofjesuschrist.org/music/library/childrens-songbook/i-am-a-child-of-god"
}

###
DELETE https://hymnapi.onrender.com/api/hymns/67a703b5936aa072f1deb89b